seznam/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stream/', include('stream.urls', namespace='stream')),
    path('', include('stream.urls', namespace='stream'))  # not needed, just to don't get 404 on home-page
]

stream/urls.py
from django.urls import path
from . import views


app_name = 'stream'
urlpatterns = [
    path('', views.show_movies, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

stream/models.py
from django.db import models


class Movie(models.Model):
    # define movie attributes - for simplicity just a few of the most important
    name = models.CharField(max_length=100)
    short_name = models.CharField(max_length=50)
    icon_uri = models.CharField(max_length=50)
    manifest_uri = models.CharField(max_length=50)
    source = models.CharField(max_length=50)
    # focus = models.BooleanField()
    # disabled = models.BooleanField()
    # extra_text = models.JSONField()
    # certificate_uri = models.CharField(max_length=50)
    # description = models.CharField(max_length=50)
    # is_featured = models.BooleanField()
    # drm = models.JSONField()
    # features = models.JSONField()
    # license_servers = models.JSONField()
    # license_request_headers = models.JSONField()
    # request_filter = models.JSONField()
    # response_filter = models.JSONField()
    # clear_keys = models.JSONField()
    # extra_config = models.JSONField()
    # ad_tag_uri = models.CharField(max_length=100)
    # ima_video_id = models.CharField(max_length=50)
    # ima_asset_key = models.CharField(max_length=50)
    # ima_content_src_id = models.IntegerField()
    # mime_type = models.CharField(max_length=50)
    # media_playlist_full_mime_type = models.CharField(max_length=50)
    # stored_progress = models.IntegerField()
    # stored_content = models.JSONField()

    def __str__(self):
        return self.name

stream/views.py
from django.shortcuts import render
from django.views import generic
from .models import Movie
from .filters import MovieFilter


def show_movies(request):
    movies = Movie.objects.all()
    if request.method == 'GET' and 'order_field' in request.GET:
        sorting_field = request.GET['order_field']
        movies = movies.order_by(sorting_field)
    filter = MovieFilter(request.GET, queryset=movies)
    context = {'filter': filter, 'movies': filter.qs}
    return render(request, 'stream/index.html', context)


class DetailView(generic.DetailView):
    model = Movie
    template_name = 'stream/detail.html'

stream/templates/stream/detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'stream/styles.css' %}">

<div class="wrapper-container">
    <h1>Stream Flix</h1>
        <div class="detail">
            <p><b>Name:</b> {{ movie.name }}</p>
            <p><b>Short name:</b> {{ movie.short_name }}</p>
            <p><b>Source:</b> {{ movie.source }}</p>
            <img class="img" src ="{{movie.icon_uri}}">
            <form>
                <button class="play">Play Movie</button>
            </form>
            </a>
        </div>
</div>

stream/templates/stream/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'stream/styles.css' %}">

<div class="wrapper-container">
    <h1>Stream Flix</h1>
    <form method="get">
        <div>
            {{ filter.form }}
            <button type="submit">Search</button>
        </div>
        <div>
            <button type="submit" name="order_field" value="name">Name Ordering</button>
            <button type="submit" name="order_field" value="short_name">Short-name Ordering</button>
            <button type="submit" name="order_field" value="source">Source Ordering</button>
        </div>
    </form>
    {% for movie in movies %}
        <div class="card">
            <a href="{% url 'stream:detail' movie.id %}">
                <img class="img" src ="{{movie.icon_uri}}">
                <p class="name">{{ movie.name }}</p>
                <p>{{ movie.source }}</p>
            </a>
        </div>
    {% endfor %}
</div>